# Gunakan image Node.js sebagai base
FROM node:20

# Set direktori kerja
WORKDIR /app

# Salin package.json dan package-lock.json
COPY package*.json ./

# Instal dependensi
RUN npm install

# Salin semua file proyek
COPY . .

# Kompilasi TypeScript ke JavaScript
RUN npm run build

# Ekspose port aplikasi (sesuaikan dengan port yang Anda gunakan)
EXPOSE 3000

# Perintah untuk menjalankan aplikasi
CMD ["npm", "run", "start"]